# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df9fa0ac898282e4953c3eeec57b1a4135b1226929b78a958160c055840c0bbbbd5f4fc7a5cf88fb4e438cc6592e9ae7365ae82417659e47ea90101ea0c69b98

test:
  secret_key_base: ef837ef57a6e4217d100337094cda894be38b0e356693ff45dfa8522e9cda21b20639cbc3a511567c31888eccee2ee983ba2a963007316743769df51cea05d48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
